# Generated by Django 3.1.3 on 2020-11-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_article_brief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_pic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
